/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewOrgRouteImport } from './routes/new-org'
import { Route as SelectOrgRouteImport } from './routes/select-org'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as DevOutboxRouteImport } from './routes/dev/outbox'
import { Route as DevResetRouteImport } from './routes/dev/reset'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as OOrgIdRouteRouteImport } from './routes/o/$orgId/route'
import { Route as PPublicSlugRouteImport } from './routes/p/$publicSlug'
import { Route as OOrgIdIndexRouteImport } from './routes/o/$orgId/index'
import { Route as OOrgIdAccountRouteImport } from './routes/o/$orgId/account'
import { Route as OOrgIdFinanceRouteImport } from './routes/o/$orgId/finance'
import { Route as OOrgIdGroupsRouteImport } from './routes/o/$orgId/groups'
import { Route as OOrgIdImportRouteImport } from './routes/o/$orgId/import'
import { Route as OOrgIdMembersRouteImport } from './routes/o/$orgId/members'
import { Route as OOrgIdNotificationsRouteImport } from './routes/o/$orgId/notifications'
import { Route as OOrgIdRehearsalsRouteImport } from './routes/o/$orgId/rehearsals'
import { Route as OOrgIdSettingsRouteImport } from './routes/o/$orgId/settings'
import { Route as OOrgIdEventsIndexRouteImport } from './routes/o/$orgId/events/index'
import { Route as OOrgIdEventsEventIdRouteImport } from './routes/o/$orgId/events/$eventId'
import { Route as ApiOrgsOrgIdAttachmentsAttachmentIdRouteImport } from './routes/api/orgs.$orgId.attachments.$attachmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewOrgRoute = NewOrgRouteImport.update({
  id: '/new-org',
  path: '/new-org',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectOrgRoute = SelectOrgRouteImport.update({
  id: '/select-org',
  path: '/select-org',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const DevOutboxRoute = DevOutboxRouteImport.update({
  id: '/dev/outbox',
  path: '/dev/outbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DevResetRoute = DevResetRouteImport.update({
  id: '/dev/reset',
  path: '/dev/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgIdRouteRoute = OOrgIdRouteRouteImport.update({
  id: '/o/$orgId',
  path: '/o/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const PPublicSlugRoute = PPublicSlugRouteImport.update({
  id: '/p/$publicSlug',
  path: '/p/$publicSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgIdIndexRoute = OOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdAccountRoute = OOrgIdAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdFinanceRoute = OOrgIdFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdGroupsRoute = OOrgIdGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdImportRoute = OOrgIdImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdMembersRoute = OOrgIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdNotificationsRoute = OOrgIdNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdRehearsalsRoute = OOrgIdRehearsalsRouteImport.update({
  id: '/rehearsals',
  path: '/rehearsals',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdSettingsRoute = OOrgIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdEventsIndexRoute = OOrgIdEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdEventsEventIdRoute = OOrgIdEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const ApiOrgsOrgIdAttachmentsAttachmentIdRoute =
  ApiOrgsOrgIdAttachmentsAttachmentIdRouteImport.update({
    id: '/api/orgs/$orgId/attachments/$attachmentId',
    path: '/api/orgs/$orgId/attachments/$attachmentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new-org': typeof NewOrgRoute
  '/select-org': typeof SelectOrgRoute
  '/verify': typeof VerifyRoute
  '/o/$orgId': typeof OOrgIdRouteRouteWithChildren
  '/dev/outbox': typeof DevOutboxRoute
  '/dev/reset': typeof DevResetRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$publicSlug': typeof PPublicSlugRoute
  '/o/$orgId/account': typeof OOrgIdAccountRoute
  '/o/$orgId/finance': typeof OOrgIdFinanceRoute
  '/o/$orgId/groups': typeof OOrgIdGroupsRoute
  '/o/$orgId/import': typeof OOrgIdImportRoute
  '/o/$orgId/members': typeof OOrgIdMembersRoute
  '/o/$orgId/notifications': typeof OOrgIdNotificationsRoute
  '/o/$orgId/rehearsals': typeof OOrgIdRehearsalsRoute
  '/o/$orgId/settings': typeof OOrgIdSettingsRoute
  '/o/$orgId/': typeof OOrgIdIndexRoute
  '/o/$orgId/events/$eventId': typeof OOrgIdEventsEventIdRoute
  '/o/$orgId/events/': typeof OOrgIdEventsIndexRoute
  '/api/orgs/$orgId/attachments/$attachmentId': typeof ApiOrgsOrgIdAttachmentsAttachmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new-org': typeof NewOrgRoute
  '/select-org': typeof SelectOrgRoute
  '/verify': typeof VerifyRoute
  '/dev/outbox': typeof DevOutboxRoute
  '/dev/reset': typeof DevResetRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$publicSlug': typeof PPublicSlugRoute
  '/o/$orgId/account': typeof OOrgIdAccountRoute
  '/o/$orgId/finance': typeof OOrgIdFinanceRoute
  '/o/$orgId/groups': typeof OOrgIdGroupsRoute
  '/o/$orgId/import': typeof OOrgIdImportRoute
  '/o/$orgId/members': typeof OOrgIdMembersRoute
  '/o/$orgId/notifications': typeof OOrgIdNotificationsRoute
  '/o/$orgId/rehearsals': typeof OOrgIdRehearsalsRoute
  '/o/$orgId/settings': typeof OOrgIdSettingsRoute
  '/o/$orgId': typeof OOrgIdIndexRoute
  '/o/$orgId/events/$eventId': typeof OOrgIdEventsEventIdRoute
  '/o/$orgId/events': typeof OOrgIdEventsIndexRoute
  '/api/orgs/$orgId/attachments/$attachmentId': typeof ApiOrgsOrgIdAttachmentsAttachmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new-org': typeof NewOrgRoute
  '/select-org': typeof SelectOrgRoute
  '/verify': typeof VerifyRoute
  '/o/$orgId': typeof OOrgIdRouteRouteWithChildren
  '/dev/outbox': typeof DevOutboxRoute
  '/dev/reset': typeof DevResetRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$publicSlug': typeof PPublicSlugRoute
  '/o/$orgId/account': typeof OOrgIdAccountRoute
  '/o/$orgId/finance': typeof OOrgIdFinanceRoute
  '/o/$orgId/groups': typeof OOrgIdGroupsRoute
  '/o/$orgId/import': typeof OOrgIdImportRoute
  '/o/$orgId/members': typeof OOrgIdMembersRoute
  '/o/$orgId/notifications': typeof OOrgIdNotificationsRoute
  '/o/$orgId/rehearsals': typeof OOrgIdRehearsalsRoute
  '/o/$orgId/settings': typeof OOrgIdSettingsRoute
  '/o/$orgId/': typeof OOrgIdIndexRoute
  '/o/$orgId/events/$eventId': typeof OOrgIdEventsEventIdRoute
  '/o/$orgId/events/': typeof OOrgIdEventsIndexRoute
  '/api/orgs/$orgId/attachments/$attachmentId': typeof ApiOrgsOrgIdAttachmentsAttachmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/new-org'
    | '/select-org'
    | '/verify'
    | '/o/$orgId'
    | '/dev/outbox'
    | '/dev/reset'
    | '/invite/$token'
    | '/p/$publicSlug'
    | '/o/$orgId/account'
    | '/o/$orgId/finance'
    | '/o/$orgId/groups'
    | '/o/$orgId/import'
    | '/o/$orgId/members'
    | '/o/$orgId/notifications'
    | '/o/$orgId/rehearsals'
    | '/o/$orgId/settings'
    | '/o/$orgId/'
    | '/o/$orgId/events/$eventId'
    | '/o/$orgId/events/'
    | '/api/orgs/$orgId/attachments/$attachmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/new-org'
    | '/select-org'
    | '/verify'
    | '/dev/outbox'
    | '/dev/reset'
    | '/invite/$token'
    | '/p/$publicSlug'
    | '/o/$orgId/account'
    | '/o/$orgId/finance'
    | '/o/$orgId/groups'
    | '/o/$orgId/import'
    | '/o/$orgId/members'
    | '/o/$orgId/notifications'
    | '/o/$orgId/rehearsals'
    | '/o/$orgId/settings'
    | '/o/$orgId'
    | '/o/$orgId/events/$eventId'
    | '/o/$orgId/events'
    | '/api/orgs/$orgId/attachments/$attachmentId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/new-org'
    | '/select-org'
    | '/verify'
    | '/o/$orgId'
    | '/dev/outbox'
    | '/dev/reset'
    | '/invite/$token'
    | '/p/$publicSlug'
    | '/o/$orgId/account'
    | '/o/$orgId/finance'
    | '/o/$orgId/groups'
    | '/o/$orgId/import'
    | '/o/$orgId/members'
    | '/o/$orgId/notifications'
    | '/o/$orgId/rehearsals'
    | '/o/$orgId/settings'
    | '/o/$orgId/'
    | '/o/$orgId/events/$eventId'
    | '/o/$orgId/events/'
    | '/api/orgs/$orgId/attachments/$attachmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NewOrgRoute: typeof NewOrgRoute
  SelectOrgRoute: typeof SelectOrgRoute
  VerifyRoute: typeof VerifyRoute
  OOrgIdRouteRoute: typeof OOrgIdRouteRouteWithChildren
  DevOutboxRoute: typeof DevOutboxRoute
  DevResetRoute: typeof DevResetRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PPublicSlugRoute: typeof PPublicSlugRoute
  ApiOrgsOrgIdAttachmentsAttachmentIdRoute: typeof ApiOrgsOrgIdAttachmentsAttachmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-org': {
      id: '/new-org'
      path: '/new-org'
      fullPath: '/new-org'
      preLoaderRoute: typeof NewOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-org': {
      id: '/select-org'
      path: '/select-org'
      fullPath: '/select-org'
      preLoaderRoute: typeof SelectOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/outbox': {
      id: '/dev/outbox'
      path: '/dev/outbox'
      fullPath: '/dev/outbox'
      preLoaderRoute: typeof DevOutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/reset': {
      id: '/dev/reset'
      path: '/dev/reset'
      fullPath: '/dev/reset'
      preLoaderRoute: typeof DevResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgId': {
      id: '/o/$orgId'
      path: '/o/$orgId'
      fullPath: '/o/$orgId'
      preLoaderRoute: typeof OOrgIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$publicSlug': {
      id: '/p/$publicSlug'
      path: '/p/$publicSlug'
      fullPath: '/p/$publicSlug'
      preLoaderRoute: typeof PPublicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgId/': {
      id: '/o/$orgId/'
      path: '/'
      fullPath: '/o/$orgId/'
      preLoaderRoute: typeof OOrgIdIndexRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/account': {
      id: '/o/$orgId/account'
      path: '/account'
      fullPath: '/o/$orgId/account'
      preLoaderRoute: typeof OOrgIdAccountRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/finance': {
      id: '/o/$orgId/finance'
      path: '/finance'
      fullPath: '/o/$orgId/finance'
      preLoaderRoute: typeof OOrgIdFinanceRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/groups': {
      id: '/o/$orgId/groups'
      path: '/groups'
      fullPath: '/o/$orgId/groups'
      preLoaderRoute: typeof OOrgIdGroupsRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/import': {
      id: '/o/$orgId/import'
      path: '/import'
      fullPath: '/o/$orgId/import'
      preLoaderRoute: typeof OOrgIdImportRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/members': {
      id: '/o/$orgId/members'
      path: '/members'
      fullPath: '/o/$orgId/members'
      preLoaderRoute: typeof OOrgIdMembersRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/notifications': {
      id: '/o/$orgId/notifications'
      path: '/notifications'
      fullPath: '/o/$orgId/notifications'
      preLoaderRoute: typeof OOrgIdNotificationsRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/rehearsals': {
      id: '/o/$orgId/rehearsals'
      path: '/rehearsals'
      fullPath: '/o/$orgId/rehearsals'
      preLoaderRoute: typeof OOrgIdRehearsalsRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/settings': {
      id: '/o/$orgId/settings'
      path: '/settings'
      fullPath: '/o/$orgId/settings'
      preLoaderRoute: typeof OOrgIdSettingsRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/events/': {
      id: '/o/$orgId/events/'
      path: '/events'
      fullPath: '/o/$orgId/events/'
      preLoaderRoute: typeof OOrgIdEventsIndexRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/events/$eventId': {
      id: '/o/$orgId/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/o/$orgId/events/$eventId'
      preLoaderRoute: typeof OOrgIdEventsEventIdRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/api/orgs/$orgId/attachments/$attachmentId': {
      id: '/api/orgs/$orgId/attachments/$attachmentId'
      path: '/api/orgs/$orgId/attachments/$attachmentId'
      fullPath: '/api/orgs/$orgId/attachments/$attachmentId'
      preLoaderRoute: typeof ApiOrgsOrgIdAttachmentsAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OOrgIdRouteRouteChildren {
  OOrgIdAccountRoute: typeof OOrgIdAccountRoute
  OOrgIdFinanceRoute: typeof OOrgIdFinanceRoute
  OOrgIdGroupsRoute: typeof OOrgIdGroupsRoute
  OOrgIdImportRoute: typeof OOrgIdImportRoute
  OOrgIdMembersRoute: typeof OOrgIdMembersRoute
  OOrgIdNotificationsRoute: typeof OOrgIdNotificationsRoute
  OOrgIdRehearsalsRoute: typeof OOrgIdRehearsalsRoute
  OOrgIdSettingsRoute: typeof OOrgIdSettingsRoute
  OOrgIdIndexRoute: typeof OOrgIdIndexRoute
  OOrgIdEventsEventIdRoute: typeof OOrgIdEventsEventIdRoute
  OOrgIdEventsIndexRoute: typeof OOrgIdEventsIndexRoute
}

const OOrgIdRouteRouteChildren: OOrgIdRouteRouteChildren = {
  OOrgIdAccountRoute: OOrgIdAccountRoute,
  OOrgIdFinanceRoute: OOrgIdFinanceRoute,
  OOrgIdGroupsRoute: OOrgIdGroupsRoute,
  OOrgIdImportRoute: OOrgIdImportRoute,
  OOrgIdMembersRoute: OOrgIdMembersRoute,
  OOrgIdNotificationsRoute: OOrgIdNotificationsRoute,
  OOrgIdRehearsalsRoute: OOrgIdRehearsalsRoute,
  OOrgIdSettingsRoute: OOrgIdSettingsRoute,
  OOrgIdIndexRoute: OOrgIdIndexRoute,
  OOrgIdEventsEventIdRoute: OOrgIdEventsEventIdRoute,
  OOrgIdEventsIndexRoute: OOrgIdEventsIndexRoute,
}

const OOrgIdRouteRouteWithChildren = OOrgIdRouteRoute._addFileChildren(
  OOrgIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NewOrgRoute: NewOrgRoute,
  SelectOrgRoute: SelectOrgRoute,
  VerifyRoute: VerifyRoute,
  OOrgIdRouteRoute: OOrgIdRouteRouteWithChildren,
  DevOutboxRoute: DevOutboxRoute,
  DevResetRoute: DevResetRoute,
  InviteTokenRoute: InviteTokenRoute,
  PPublicSlugRoute: PPublicSlugRoute,
  ApiOrgsOrgIdAttachmentsAttachmentIdRoute:
    ApiOrgsOrgIdAttachmentsAttachmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
